### ISSUE TITLE
solr index: parentUri in sub and proxy objects

### ISSUE THREAD

**Issue by bramdvrepublic** [republic-of-reinvention/com.stralo.framework#94]
After a recent update,
indexed objects with

> resourceType:SUB 

have a parentUri
However, objects with

> resourceType:PROXY

do not have a parentUri. They do have a _nest_parent_

**Comment by bramdvrepublic** [comment]
Example of a PROXY not having a parentUri:

 {
        "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Satellite%20image%20of%20France%20in%20August%202002.jpg",
        "language":"en",
        "resource":"/resource/WikidataCountry/Q142",
        "uri":"/resource/WikidataCountry/Q142",
        "label":"France",
        "typeOf":"crb:WikidataCountry",
        "resourceType":"PROXY",
        "_nest_parent_":"/resource/1176587111159013241",
        "_version_":1645588200447541248},
      {

**Comment by beligum** [comment]
This kind of exposed a critical flaw in our design: because we re-use the uri of the page in our proxy entries, we effectively allowed to create two objects with the same uniqueKey....

Also see https://github.com/republic-of-reinvention/com.stralo.framework/issues/50#issuecomment-535430446
and
https://github.com/republic-of-reinvention/com.stralo.framework/issues/68

In other words, we had to introduce a new field in our index (a true "id" field) that is auto-filled with UUID values, because our existing strategy was bugged.

On the matter at hand: the parentUri of the resource proxy is just copied from the resource itself (ResourceProxy interface). But when we use it in the context of the nested document, it becomes dubious: is the parentUri pointing to the root document (the one the nested proxy is part of), of should it point to the original parentUri of the resource (see https://github.com/republic-of-reinvention/com.stralo.framework/issues/68)?

Since the proxy doc now has a different id than the original resource (but the same uri), is clearly marked as a PROXY, we have a use case ready for it right now and the functionality of https://github.com/republic-of-reinvention/com.stralo.framework/issues/68 isn't active yet, we decided to overwrite any (possible existing) parentUri field of the resource proxy with the uri of the document it is indexed in.
